version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ka_user
      POSTGRES_PASSWORD: ka_pass
      POSTGRES_DB: ka_cobrancas
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ka_cobrancas
      - SPRING_DATASOURCE_USERNAME=ka_user
      - SPRING_DATASOURCE_PASSWORD=ka_pass
    ports:
      - "8081:8081"
  frontend:
    build: ./frontend
    ports:
      - "8088:80"
    depends_on:
      - backend
volumes:
  pgdata:  # <--- CORREÇÃO: AGORA O VOLUME 'PGDATA' ESTÁ DEFINIDO CORRETAMENTE